"""Initial migration

Revision ID: 9280bd8c9a83
Revises: 
Create Date: 2017-12-28 23:44:14.544622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9280bd8c9a83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('publish_date', sa.DateTime(), nullable=True))
    op.drop_column('posts', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_date', mysql.DATETIME(), nullable=True))
    op.drop_column('posts', 'publish_date')
    # ### end Alembic commands ###
